USE [master]
GO

/****** Object:  Database [BD_DELTA]    Script Date: 27/11/2023 22:11:46 ******/
CREATE DATABASE [BD_DELTA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_DELTA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BD_DELTA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_DELTA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BD_DELTA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_DELTA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_DELTA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_DELTA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_DELTA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_DELTA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_DELTA] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_DELTA] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BD_DELTA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_DELTA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_DELTA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_DELTA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_DELTA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_DELTA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_DELTA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_DELTA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_DELTA] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BD_DELTA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_DELTA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_DELTA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_DELTA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_DELTA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_DELTA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_DELTA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_DELTA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BD_DELTA] SET  MULTI_USER 
GO

ALTER DATABASE [BD_DELTA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_DELTA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_DELTA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_DELTA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BD_DELTA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_DELTA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BD_DELTA] SET QUERY_STORE = ON
GO

ALTER DATABASE [BD_DELTA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [BD_DELTA] SET  READ_WRITE 
GO

